services:
  pgdatabase:
    image: postgres:16
    environment:
      - POSTGRES_USER=roots
      - POSTGRES_PASSWORD=roots
      - POSTGRES_DB=green_ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5431:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=roots
    ports:
      - "8080:80"
    volumes:
      -"./ny_taxi_postgres_data:/var/lib/pgadmin"